### ISSUE TITLE
Crash using pads on newly imported wav samples

### ISSUE THREAD

**Issue by GusGranite** [olympianoiseco/Patterning-2-Public#102]
10.5 Pro iOS 11.4.1

**Comment by olympianoiseco** [comment]
Hi could you locate crash logs on your device so I can see if this is related to other crashes?

Navigate to your device Settings > Privacy > Analytics > Analytics Data.
Scroll through this list to find Patterning 2 events. See screen shot below. The list is alphabetical. 
Tap one of these events. 
Tap the share icon at the top right, send to
support@olympianoiseco.com  
re:Issue #102

**Comment by olympianoiseco** [comment]
I see you have two different crashes you are experiencing.  It's quite possible they are related, please send me all the crash logs you have on your device.

**Comment by olympianoiseco** [comment]
same as #89
