### ISSUE TITLE
Pattern naming/renaming

### ISSUE THREAD

**Issue by mibolux** [olympianoiseco/Patterning-2-Public#111]
I would like to see a possibility to name a pattern or rename it. A A1... is not very helpfull for me especially if A1 is supposed to be C.

Great App! keep on...

www.mibo.lu

**Comment by olympianoiseco** [comment]
Thanks, I'm closing this as similar to #48

**Comment by nathankopp** [comment]
AGREED! This seems like it would be pretty easy, and would make managing longer songs MUCH easier!

**Comment by nathankopp** [comment]
Reordering (from #48) would also be very helpful. For the UX, I'd recommend adding drag-and-drop to the top part of the "song" tab.  Maybe have it work similar to the (x) button, where you hold the move button and then drag a pattern circle to a new location in the list.

For rename, maybe on the song screen you can double-tap one of the circles to bring up a modal box for entering the new name.
