### ISSUE TITLE
Dropbox import

### ISSUE THREAD

**Issue by mibolux** [olympianoiseco/Patterning-2-Public#118]
The Dropbox sample import is very hazardeous here, sometimes the samples load, sometimes not! Especially when loading them to subfolders. Also the folder icon on the right side is this a copy pr move function, as the sanples appear then in the folder and in the user samples...

**Comment by olympianoiseco** [comment]
The folders aren't actually moving the files -- they are more like tags actually.  So a sample can exist in multiple "folders."

Can you give me steps to reproduce the issue with samples not loading?  I haven't been able to reproduce it.

**Comment by mibolux** [comment]
Hello,

The files just don’t appear in the folders first. After changing to all samples or user samples they appear finally, but most of the time they appear several times the same sample (maybe because I imported several times as I did not see them)

**Comment by olympianoiseco** [comment]
Ah ok, it sounds like more of an issue with the samples not showing up correctly in the library rather than that they are not imported.  I'll check it out.

**Comment by olympianoiseco** [comment]
It sounds like what you are wanting to do is have the files import immediately into the current folder?  That would be neat, but it's not the way it works right now.  I can add that as a feature request.
