### ISSUE TITLE
MIDI output presets

### ISSUE THREAD

**Issue by mwkohout** [olympianoiseco/Patterning-2-Public#122]
I'm using Patterning to sequence my external drum machines.

I may have missed it, but it would be great to midi learn so that the midi note values for each instrument could be more easily mapped to specific loop.

It would also be useful(maybe even more useful) to have something like a midi device library so different mappings could be stored and centerally managed as something different than just a part of a pattern/loop.

**Comment by olympianoiseco** [comment]
I think what you are asking here is to be able to set different MIDI outputs on different Patterns.  If so, that can be accomplished using Drum Kit swapping.  See the tutorial video from the ? menu for how to use that.  It works with MIDI outs as well.  

MIDI device presets sounds like a useful idea.
