### ISSUE TITLE
Track Output all layers to MIDI

### ISSUE THREAD

**Issue by waveslice** [olympianoiseco/Patterning-2-Public#125]
#feature-request
I would like to record complete MIDI sequences coming from Patterning 2 but it only sends out one note to Auria Pro.  As a result Auria Pro records the MIDI for only one layer.  Please add the feature to send all layers combined as chords to external DAWs (on MIDI channel 10?).

**Comment by olympianoiseco** [comment]
Make sure all of your tracks are correctly set up to send MIDI, there is no reason why they can’t all be recorded used the same output port and channel.

**Comment by waveslice** [comment]
Thanks.  Didn't realize it was set per layer individually.
