### ISSUE TITLE
Exporting individual tracks with multiple drum kits does not work

### ISSUE THREAD

**Issue by Audiogus** [olympianoiseco/Patterning-2-Public#136]
-I have two patterns alternating on the song timeline.  

-Each pattern is of the minimum length. 

-When I export inidivdual tracks the exports are either all completely blank or just copies of the master track.

**Comment by olympianoiseco** [comment]
Thanks, Can you help me investigate this by sending me the .onps file of the project at support@olympianoiseco.com 

Also attach a screenshot of the export settings you are using.  Thanks!

**Comment by Audiogus** [comment]
Sent an email

**Comment by olympianoiseco** [comment]
Think I've got this one sorted out.  The way tracks were being muted for the bounces didn't take into account the new way in which the drum kits are loaded.  Look for fix in next update.
