### ISSUE TITLE
Samples fail to load

### ISSUE THREAD

**Issue by Audiogus** [olympianoiseco/Patterning-2-Public#137]
At a certain point samples fail to load.  If I save the drumkit and reload the scene the new samples are present.

**Comment by olympianoiseco** [comment]
Any more clues about how to recreate this?

**Comment by Audiogus** [comment]
It just seems to happen sporadicly.  I’ll play around a bit and see if I can repro it.

**Comment by RostislavKryukov** [comment]
Have the very same issue with patterning 1.

**Comment by Audiogus** [comment]
Rumour has it this bug is most prevalent when it is hosted as an IAA device.

**Comment by olympianoiseco** [comment]
Same as #138
