### ISSUE TITLE
UI updates not reflected in audio output.

### ISSUE THREAD

**Issue by Audiogus** [olympianoiseco/Patterning-2-Public#138]
-values do not update properly 
-at times I will have a blank circle yet old cc data is being sent.  If I swipe up on the circle to fill everything and then swipe down to clear it, that may actually clear it.
-may be related to drumkit swapping?

**Comment by olympianoiseco** [comment]
Thanks.  

Can you just confirm for the that no other tracks are also send MIDI CC on the same channel.
For example if both tracks 1&2 are using MIDI Port X on Channel 1, they could both potentially send MIDI CC at the same time.  I want to make sure that's not what's going on here!

**Comment by Audiogus** [comment]
It definitely is not on other tracks because I can clear it eventually so that no CC are playing just by swiping up and down on the slots of the same circle.  As I mentioned the circle appears like everything is at zero but I need to swipe up (set a value) and then back down again (to zero) to ensure it actually sets to zero.

**Comment by Audiogus** [comment]
Well it seems that when the problem happens I am unable to update anything, meaning note changes, cc, loading different samples etc.  Visualy everything updates but no actual data changes until I save the song then it all instantly updates and works properly again.

(It is probably unrelated but I am using multitrack outputs into AUM (shoulder shrug)...)

**Comment by olympianoiseco** [comment]
Thanks for this - I’ve been trying to track this issue down for awhile actually, but can’t figure out how to reproduce it.  Any insight into when it starts to happen?

**Comment by Audiogus** [comment]
Rumour has it this bug is most prevalent when it is hosted as an IAA device.

**Comment by olympianoiseco** [comment]
Ok, thanks -- where are these rumors happening so I can ask more questions? :) 

I'm putting up a new beta right now that has some additional debugging tools in it.  If you (or any one else) would be so kind as to join the beta test, I can invite you and give you instructions.  Thanks!

**Comment by olympianoiseco** [comment]
Here's another description of the bug.
> Most of the times when i'm playing around with like adding steps or switching drumkits in the shortcut menu, the chances are not recognized. I came across the solution that when hitting the save button it magically get the premade changes. Thant means when i hit the save button the app works as promised but after the next start of the app it's the same behaviour again.  Basically all interactive elements like adding a step, changing the drumkit etc. won't get recognized until i actively press the save button.

**Comment by olympianoiseco** [comment]
@Audiogus which iPad and iOS are you running?

**Comment by olympianoiseco** [comment]
I've created a beta version with some debugging built in.  Let me know if anyone wants to join the beta and help track it down.

**Comment by olympianoiseco** [comment]
Fixed in 2.1
