### ISSUE TITLE
“Oops. Failed to open project file”

### ISSUE THREAD

**Issue by cooneypiano** [olympianoiseco/Patterning-2-Public#163]
Whenever I try to export a file to Ableton live set, both in patterning 1 and 2, I get the message “oops. Failed to open project file.” Is this a bug? Am I doing something wrong?

**Comment by Rotee** [comment]
No problem here - what version do you use?
Which iPad / which iOS?
Have you checked the space available?
Where do you want to save?

**Comment by cooneypiano** [comment]
Thanks for the fast response. I have an iPad mini running 12.3.1. I have 3 gigs of free space on the iPad. The app does not give me an option of where to save... I get the error message before that. I would like to save to my GDrive app.

**Comment by Rotee** [comment]
Have you checked that export in 60 sec video:
https://youtu.be/k-vvOk2Ub3A

**Comment by cooneypiano** [comment]
Yes.

**Comment by olympianoiseco** [comment]
Just replied on the forum - do you get this error when you open it in ableton or during the export process in Patterning?

**Comment by cooneypiano** [comment]
I get the error in patterning, during the export process. After the graphic of the spinning circles I get the message, “oops. Failed to open file.” I never get to the menu where I am to choose where to save the file.

**Comment by olympianoiseco** [comment]
Ok, can you send me the .onps file so I can try it myself?

**Comment by olympianoiseco** [comment]
support@olympianoiseco.com

**Comment by Rotee** [comment]
Could you post here the export window please?
Do you use a similar selection?

**Comment by cooneypiano** [comment]
My export window looks exactly like that. I took a video of the problem but can’t figure out how to attach that here.... I find iOS devices mostly impossible for doing simple file management things.

**Comment by Rotee** [comment]
Have you tried with a new project - just a pretty basic and small one?

**Comment by cooneypiano** [comment]
I hadn’t tried that, so I just did. And yes I can export a very simple project.

**Comment by Rotee** [comment]
Another idea - have you saved the file before export?

**Comment by cooneypiano** [comment]
Yes. I have saved before export.

**Comment by olympianoiseco** [comment]
Please try renaming your project -- the `/` character is probably making the file fail to save (it thinks it's a folder)

**Comment by olympianoiseco** [comment]
I can confirm that renaming it to `98 grooves` rather than `9/8 grooves` fixes the issue.

**Comment by olympianoiseco** [comment]
Of course, this is a bug that I will fix in an update.

**Comment by cooneypiano** [comment]
Great! That fixed it for me. Thanks!
