### ISSUE TITLE
CC eraser bug

### ISSUE THREAD

**Issue by svervs** [olympianoiseco/Patterning-2-Public#168]
Hey crew,

when using CC layers, the eraser doesn't set the steps back to 0, needs to be done with the pencil.

Here's a shitty video
https://www.dropbox.com/s/yy6bw28c9r43hh3/PatBug.mov

Thanks!

**Comment by olympianoiseco** [comment]
This is not a bug. 

There is a subtle difference between using the eraser and the pen tool with CCs, which should explain the behavior you are seeing.  

Using the eraser will disable the step for the CC, which means that no CC will be sent on that step.

Using the pen tool will (in this case) tell the layer to send a CC of zero of that step.

**Comment by svervs** [comment]
Ah, Ok I see ... didn't check the manual.
A bit confusing. Maybe having a change of color or opacity for muted steps would make it more obvious.

Thanks!
