### ISSUE TITLE
Song Mode Broken After Update.

### ISSUE THREAD

**Issue by Jaraon** [olympianoiseco/Patterning-2-Public#169]
Hi, 

I thought to report in here. My song mode appears to be broken or is corrupted after the latest update. I listed some of the symptoms below.

Previously saved songs work correctly until editing or creating new arrangements. I created a completely new project and song arrangement and had the same results.

Oddly, if I completely close patterning or save and reopen the project it will work as expected. If I save in place while working it does not correct the problem so reopening the project or program seems to be the only thing that will clear the issue.

Here are a few examples of the song mode problems: 

1.) Song plays in the wrong pattern order and/or display the incorrect patterns being triggered.

2.) The first pattern in the song will play and the next several blocks will be silent until looping back to the first pattern. It displays the first pattern playing the entire time while cycling through the different pattern blocks below.

3.) Songs will play in a previously erased pattern order while displaying the current arrangement. 

4.) The reset rotation function will display patterns not currently in the song arrangement.

Also, some saved patterns choke differently after the update though its definitely an overall improvement. I noticed some tracks playing in different cycles than they used to and the chocks being extremely tight, creating short chirping type sounds regardless of changes to eq, decay, tuning, etc. Im pushing the program so I'm not sure if it is really a bug or not.

Patterning is a fantastic program! Hope any of this helps!

**Comment by olympianoiseco** [comment]
Thanks this is fixed in 2.1.4 which came out today.  Please update and let me know if it’s not fixed!

**Comment by Jaraon** [comment]
Just updated! No issues so far.

Thank you!
