### ISSUE TITLE
Song page feature requests

### ISSUE THREAD

**Issue by artefact2001** [olympianoiseco/Patterning-2-Public#37]
Double clicking on pattern graphic opens pattern page.
Consider changing naming ‘song’ becomes ‘track’?

**Comment by olympianoiseco** [comment]
re : Consider changing naming ‘song’ becomes ‘track’?
I assume we are talking about the menu bar.  I'm considering the idea that it could be changed to "TIMELINE," however, the word "SONG" encompasses both the idea of the timeline and the "PATTERNS" switching view, which are both on the SONG screen.  I don't think the word "TRACK" adds clarity. 

I don't see a huge benefit of adding double tap to bring up pattern -- it's also two taps to select a pattern and then switch to the pattern screen.
