### ISSUE TITLE
Monophonic tracks

### ISSUE THREAD

**Issue by aplourde72** [olympianoiseco/Patterning-2-Public#75]
To allow choking of longer samples without using one of the two choke groups (or just have more choke groups)

**Comment by jaspermiddelberg** [comment]
Yes please, 4 choke groups would be nice, i like moving in pairs.

**Comment by aplourde72** [comment]
As an update to this: choke groups don't affect mono / poly playback per track, so true monophonic playback would be very useful when using longer samples where you want it to "self-choke"

**Comment by olympianoiseco** [comment]
Yea the limiting issue here is backwards compatibility.  Making choke groups work this way would change existing patterns.  So it actually needs to be a separate parameter.

**Comment by breskar** [comment]
A separate parameter for monophonic sample playback would be great.
