### ISSUE TITLE
Tutorial videos don't show up on iPad Pro 12.9 iOS10.3.3 - works now

### ISSUE THREAD

**Issue by Rotee** [olympianoiseco/Patterning-2-Public#81]
While the list of tutorial videos shows up perfectly on my iPad Air iOS 10.3.3 and my iPad 2017 with iOS 11 it doesn't show up on iPad Pro 12.9 iOS 10.3.3 though
It looks like
![img_0471](https://user-images.githubusercontent.com/40961231/43243154-6ab04106-90a5-11e8-9b19-7dfc660a0161.PNG)

**Comment by olympianoiseco** [comment]
Can you check again?  If you tap the help button before it has a chance to download the data it might not show up.

**Comment by olympianoiseco** [comment]
Great.  Thanks for checking.  To be clear, it downloads a list of videos on app launch.  If you aren't connected to the internet, the list won't appear.  If you check the list of videos within the first couple seconds after app launch, they might not appear also, as the list hasn't been downloaded.  But it should appear if you wait 10 seconds or so and try again.

**Comment by Rotee** [comment]
You're welcome - sorry for that false alarm - I understand now how that works
