### ISSUE TITLE
Drum names all change to drum being edited

### ISSUE THREAD

**Issue by astromyrmex** [olympianoiseco/Patterning-2-Public#85]
![71872a5f-d546-4d38-a72b-8e1e5f8e557f](https://user-images.githubusercontent.com/41790336/43321204-09ba83b2-91a3-11e8-9cc8-1f1c7ce5c38e.png)
![fcdb2712-a0e6-4df2-baf2-baef916981ef](https://user-images.githubusercontent.com/41790336/43321205-09e52be4-91a3-11e8-9b68-f56e1d32bd57.png)
![Uploading E757D138-F1FA-45B0-9BC1-48834DD98A74.png…]()

**Comment by olympianoiseco** [comment]
In this example, are those pads all using the same sample?  Or different ones?  If they are all the same sample, then they will all be name the same, as the track names are tied to the name of the sample.

**Comment by astromyrmex** [comment]
They are all different. As soon as I started to edit the first drum, the
others took the sample name of that drum but kept their original sounds.

**Comment by olympianoiseco** [comment]
Ok, that sounds strange.  I can't reproduce it.  Could you possibly export the song (.onps) and share with me at support@olympianoiseco.com.  Also perhaps a video of it happening?  That will help, thanks!

**Comment by olympianoiseco** [comment]
Thanks for sending the file, I see the issue :

In this case, you are using the same sample, but with different start and end points.  As such, Patterning still names the tracks as the same sample.  You can use the EDIT>CROP TO NEW SAMPLE to make them each into their own sample.  From there, renaming them will only affect the cropped version!

**Comment by astromyrmex** [comment]
I see. So that cloud kit was one sample, cropped for each drum. That makes
sense.

Thanks!

**Comment by olympianoiseco** [comment]
Ah yes, it was!  Didn't realize that it was a cloud kit.
