### ISSUE TITLE
App crashes out when choosing new drum sample

### ISSUE THREAD

**Issue by astromyrmex** [olympianoiseco/Patterning-2-Public#89]
![9e87a64b-dba0-4927-8726-e8c829ed90c8](https://user-images.githubusercontent.com/41790336/43342470-ab2b4ff6-91da-11e8-9680-21999069091c.png)

The app has occasionally completely crashed out and has to be relaunched when I’m choosing a new sample for any of the drum slots. Grab shows process I’m in when this happens. Once relaunched, I can choose a sample for that slot without issue.

**Comment by olympianoiseco** [comment]
Thanks for report.  I have a sneaking suspicion that I’ve seen crash logs for this one.  Can you tell me, does it only happen while the app is playing?  Specifically, triggering the current sample as it’s being loaded?

**Comment by astromyrmex** [comment]
Yes, it happens while playing and while triggering the sample as it’s being
loaded.

**Comment by olympianoiseco** [comment]
@astromyrmex I'm unable to reproduce.  Can you tell me which device and iOS version you are on?  
Also, on iOS System Preferences > Patterning 2, can you "Enable Debug Logging" and then recreate the crash for me a couple times?  I can then get some logs from your device.

**Comment by astromyrmex** [comment]
iOS 11.4.1, iPad 5th generation,128GB. Have turned on debugging.

**Comment by astromyrmex** [comment]
How do I export the logs? It just happened again. Once the app quit, second
time all audio cut out but app remained active.

**Comment by olympianoiseco** [comment]
There is a new app version coming out today (hopefully) that should have this problem fixed.  If it happens again after that update let me know.

You can help me by going to system preferences > patterning 2 > enable debug logging.

**Comment by astromyrmex** [comment]
I turned on logging based on what you recommended last time. Today’s crash
and mute was using the new version which I downloaded from the App Store
just recently.

**Comment by olympianoiseco** [comment]
Thanks.  2.0.5 is the new one that should fix it.  Not out yet.

**Comment by astromyrmex** [comment]
Thanks. I eventually found all the logs under Privacy/Analytics but there
aren't any shown for Patterning, even though logging has been turned on
since the first version.
