### ISSUE TITLE
live recording beats via midi

### ISSUE THREAD

**Issue by bc373** [olympianoiseco/Patterning-2-Public#93]
this is one of my favorite new features but might it be possible to have a better visual indicator  when the pattern comes back around to the "one"? the built in metronome kind of gives this indication where the "one" is with the higher pitched beep, but it would be nice if you actually see the actual circular pattern somewhere when you are on the "record" tab. thanks!!

**Comment by olympianoiseco** [comment]
The loop indicators where accidentally hidden in the launch version.  Fixed in 2.0.4

**Comment by bc373** [comment]
Thanks so much, knew you were on it!

Bc3
